# Generated by Django 3.0.8 on 2020-07-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('alias', models.ManyToManyField(to='movies_company.Alias')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('release_year', models.PositiveIntegerField()),
                ('casting', models.ManyToManyField(related_name='movies_as_actor_actress', to='movies_company.Person')),
                ('directors', models.ManyToManyField(related_name='movies_as_director', to='movies_company.Person')),
                ('producers', models.ManyToManyField(related_name='movies_as_producer', to='movies_company.Person')),
            ],
        ),
    ]
