# Generated by Django 3.0.8 on 2020-08-02 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Aliases',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('aliases', models.ManyToManyField(to='movies_company.Alias')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('release_year', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3999), django.core.validators.MinValueValidator(1)])),
                ('casting', models.ManyToManyField(related_name='movies_as_actor_actress', to='movies_company.Person', verbose_name='Casting (Actors + Actresses)')),
                ('directors', models.ManyToManyField(related_name='movies_as_director', to='movies_company.Person')),
                ('producers', models.ManyToManyField(related_name='movies_as_producer', to='movies_company.Person')),
            ],
        ),
    ]
