# Generated by Django 3.0.8 on 2020-07-31 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='alias',
            new_name='aliasses',
        ),
    ]
