# Generated by Django 3.0.8 on 2020-08-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'verbose_name_plural': 'Aliases'},
        ),
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
