# Generated by Django 3.0.8 on 2020-08-02 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_company', '0002_auto_20200802_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
